{
  "comments": [
    {
      "key": {
        "uuid": "d36644bc_27a2d6c5",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 11,
      "author": {
        "id": 1136110
      },
      "writtenOn": "2017-10-20T16:26:15Z",
      "side": 1,
      "message": "Were you going to fill this in? Do we understand why the test failed before?",
      "range": {
        "startLine": 11,
        "startChar": 19,
        "endLine": 11,
        "endChar": 42
      },
      "revId": "6233e8d1364918639e0ee46685c4fe3957487dde",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}