This is a testharness.js-based test.
Harness Error. harness_status.status = 1 , harness_status.message = 11 duplicate test names: "start: errors in start cause WritableStream constructor to throw", "close: throwing method should cause writer close() and ready to reject", "close: returning a rejected promise should cause writer close() and ready to reject", "close: throwing getter should cause writer close() to reject", "write: throwing getter should cause write() and closed to reject", "write: throwing method should cause write() and closed to reject", "write: returning a promise that becomes rejected after the writer write() should cause writer write() and ready to reject", "write: returning a rejected promise (second write) should cause writer write() and ready to reject", "abort: non-function abort method with .apply", "abort: throwing getter should cause abort() and closed to reject", "abort: throwing method should cause abort() and closed to reject"
PASS start: errors in start cause WritableStream constructor to throw 
PASS close: throwing method should cause writer close() and ready to reject 
PASS close: returning a rejected promise should cause writer close() and ready to reject 
PASS close: throwing getter should cause writer close() to reject 
PASS write: throwing getter should cause write() and closed to reject 
PASS write: throwing method should cause write() and closed to reject 
PASS write: returning a promise that becomes rejected after the writer write() should cause writer write() and ready to reject 
PASS write: returning a rejected promise (second write) should cause writer write() and ready to reject 
PASS abort: non-function abort method with .apply 
PASS abort: throwing getter should cause abort() and closed to reject 
PASS abort: throwing method should cause abort() and closed to reject 
PASS Untitled 
PASS start: errors in start cause WritableStream constructor to throw 
PASS close: throwing method should cause writer close() and ready to reject 
PASS close: returning a rejected promise should cause writer close() and ready to reject 
PASS close: throwing getter should cause writer close() to reject 
PASS write: throwing getter should cause write() and closed to reject 
PASS write: throwing method should cause write() and closed to reject 
PASS write: returning a promise that becomes rejected after the writer write() should cause writer write() and ready to reject 
PASS write: returning a rejected promise (second write) should cause writer write() and ready to reject 
PASS abort: non-function abort method with .apply 
PASS abort: throwing getter should cause abort() and closed to reject 
PASS abort: throwing method should cause abort() and closed to reject 
PASS start: errors in start cause WritableStream constructor to throw 
PASS close: throwing method should cause writer close() and ready to reject 
PASS close: returning a rejected promise should cause writer close() and ready to reject 
PASS close: throwing getter should cause writer close() to reject 
PASS write: throwing getter should cause write() and closed to reject 
PASS write: throwing method should cause write() and closed to reject 
PASS write: returning a promise that becomes rejected after the writer write() should cause writer write() and ready to reject 
PASS write: returning a rejected promise (second write) should cause writer write() and ready to reject 
PASS abort: non-function abort method with .apply 
PASS abort: throwing getter should cause abort() and closed to reject 
PASS abort: throwing method should cause abort() and closed to reject 
PASS start: errors in start cause WritableStream constructor to throw 
PASS close: throwing method should cause writer close() and ready to reject 
PASS close: returning a rejected promise should cause writer close() and ready to reject 
PASS close: throwing getter should cause writer close() to reject 
PASS write: throwing getter should cause write() and closed to reject 
PASS write: throwing method should cause write() and closed to reject 
PASS write: returning a promise that becomes rejected after the writer write() should cause writer write() and ready to reject 
PASS write: returning a rejected promise (second write) should cause writer write() and ready to reject 
PASS abort: non-function abort method with .apply 
PASS abort: throwing getter should cause abort() and closed to reject 
PASS abort: throwing method should cause abort() and closed to reject 
Harness: the test ran to completion.

